# site properties and page defaults
title: SDU SMILE Group
subtitle: We SMILE (SocialMetabolic Analytics for Sustainability)- and strive to map and inform a circular, low-carbon, and just sociometabolic transition
description: We are a research team from the Life-Cycle Engineering Unit, Department of Green Technology, University of Southern Denmark
header: images/odense.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: wuc@igt.sdu.dk
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: sdu-mfa
  twitter: sdu-mfa
  youtube: sdu-mfa

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff


